### ISSUE TITLE
Transfer of this repo

### ISSUE THREAD

**Issue by Neustradamus** [djabberd/DJabberd-RosterStorage-AD#1]
Hello @vlet,

I would like to move this old repo into djabberd organization.

What do you think?

Thanks in advance.

**Comment by vlet** [comment]
Hi, sorry for late response. So, what i need to do?

**Comment by Neustradamus** [comment]
@vlet: Thanks for your reply!

If you are ok, give me all rights in this repo, I will do the transfer, same for "SASL-NTLM" :)

**Comment by Neustradamus** [comment]
@vlet: Thanks for invitations but I have not all rights :/

**Comment by Neustradamus** [comment]
@vlet: Thanks it is now done :)
